### ISSUE TITLE
有成绩没有学分怎么办？我都不知道竟然还有这种情况。还有成绩写中、及格这种的呢？

### ISSUE THREAD

**Issue by mchotdograp** [sndnyang/superbGPACalculator#2]
rt
![微信图片_20230923211930](https://github.com/sndnyang/superbGPACalculator/assets/48815225/8a33f403-977c-4a30-a6a4-d640f95c54da)
![QQ截图20230923212011](https://github.com/sndnyang/superbGPACalculator/assets/48815225/a2a518f2-2a80-4984-9e01-813a160c803d)

**Comment by sndnyang** [comment]
合格/不合格 这种分数 应该有标准， 学校没有官方英文成绩单的话， 成绩单认证的机构也不会在这种上坑你
优良中及格差 不就是4分制的 43210嘛
没学分当然最好是问学校
